#=================================================
#   Description: Build OpenWrt using GitHub Actions
#   Lisence: MIT
#   Author: P3TERX
#   Blog: https://p3terx.com
#=================================================

name: OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install g++ libncurses5-dev libncurses5-dev zlib1g-dev bison flex unzip autoconf gawk make gettext gcc binutils patch bzip2 libz-dev asciidoc subversion wget curl git libssh-dev

    - name: Clone source code
      run: |
        git clone https://gitee.com/xiongchao/openwrt_cc1.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        cp .config openwrt
        cd openwrt
        make defconfig

    - name: Download package
      run: |
        ls -l
        cd openwrt && make download -j8 && ls -l dl
        tar -czvf myetc.tar.gz dl
        mkdir -p /opt/images
        pwd
        sudo mv -f /home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/myetc.tar.gz /opt/images/

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Frp-packages
        path: /opt/images/
